config/routes.rb
# == Route Map
#
#                           Prefix Verb     URI Pattern                             Controller#Action
#                 new_user_session GET      /users/sign_in(.:format)                devise/sessions#new
#                     user_session POST     /users/sign_in(.:format)                devise/sessions#create
#             destroy_user_session DELETE   /users/sign_out(.:format)               devise/sessions#destroy
# user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)          users/omniauth_callbacks#passthru
#  user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format) users/omniauth_callbacks#facebook
#                new_user_password GET      /users/password/new(.:format)           devise/passwords#new
#               edit_user_password GET      /users/password/edit(.:format)          devise/passwords#edit
#                    user_password PATCH    /users/password(.:format)               devise/passwords#update
#                                  PUT      /users/password(.:format)               devise/passwords#update
#                                  POST     /users/password(.:format)               devise/passwords#create
#         cancel_user_registration GET      /users/cancel(.:format)                 devise/registrations#cancel
#            new_user_registration GET      /users/sign_up(.:format)                devise/registrations#new
#           edit_user_registration GET      /users/edit(.:format)                   devise/registrations#edit
#                user_registration PATCH    /users(.:format)                        devise/registrations#update
#                                  PUT      /users(.:format)                        devise/registrations#update
#                                  DELETE   /users(.:format)                        devise/registrations#destroy
#                                  POST     /users(.:format)                        devise/registrations#create
#                             root GET      /                                       pages#home
#                           groups POST     /groups(.:format)                       groups#create
#                        new_group GET      /groups/new(.:format)                   groups#new
#                            meals GET      /meals(.:format)                        meals#index
#                                  POST     /meals(.:format)                        meals#create
#                         new_meal GET      /meals/new(.:format)                    meals#new
#                        edit_meal GET      /meals/:id/edit(.:format)               meals#edit
#                             meal GET      /meals/:id(.:format)                    meals#show
#                                  PATCH    /meals/:id(.:format)                    meals#update
#                                  PUT      /meals/:id(.:format)                    meals#update
#                                  DELETE   /meals/:id(.:format)                    meals#destroy
#

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :groups do
    get 'users', defaults: { format: :json }
  end

  resources :meals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Group < ApplicationRecord
  has_many :groups_users, dependent: :destroy
  has_many :users, through: :groups_users
  has_many :meals, dependent: :destroy
  accepts_nested_attributes_for :groups_users, reject_if: :all_blank, allow_destroy: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
    @users = User.where.not(id: current_user.id)
  end

  def create
    @group = Group.new(group_params)
    @group.users << current_user

    if @group.save
      redirect_to meals_path, notice: "Group Created!"
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:group_id])
  end

  def users
    @users = Group.find(params[:group_id]).users
  end

   def edit
    @group = Group.find(params[:id])
    @users = User.where.not(id: current_user.id)
  end

  def update
    @group = Group.find(params[:id])
    @group.users << current_user


    if @group.update(group_params)
      redirect_to meals_path
    else
      redirect_to new_group_path(@meal), error: "Group couldn't be created"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    redirect_to meals_path

  end

  private

  def group_params
    params.require(:group).permit(:name, groups_users_attributes: [:id, :user_id, :_destroy])
  end

end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.input :name, label: "Group Name" %>

  <div id="groups_users">
    <%= f.simple_fields_for :groups_users do |user| %>
      <%= render 'groups_user_fields', f: user %>
    <% end %>

    <div class="links form-group">

      <div class= "green-hover">
        <%= link_to_add_association f, :groups_users, class: "add" do %>
          <i class="fa fa-user-plus"></i>
        <% end %>
      </div>

    </div>

  </div>

  <div class="center-btn">
    <%= f.submit 'Save Group', class: "btn btn-primary" %>
  </div>

<% end %>

app/views/groups/_groups_user_fields.html.erb
<div class="row">
  <div class="nested-fields">
    <div class="col-xs-9">
      <%= f.input :user_id, collection: @users, label_method: :username, label: false, class: "" %>
    </div>
    <div class="col-xs-3">

      <%= link_to_remove_association "", f, class: "fa fa-user-times remove" %>

    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
      <div class ="group-heading">
        <h1>Edit <%= @group.name %></h1>
        <i class="fi flaticon-people-4"></i>
      </div>
      <%=  render 'form' %>

      <div class="right-align">
        <%=  link_to group_path, method: :delete, class: "remove left-align" do %>
          <i class="fa fa-trash-o"></i>
          Delete Group
        <% end %>
      </div>

    </div>
  </div>

</div>

app/views/groups/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
      <div class ="group-heading">
        <h1>New Group</h1>
        <i class="fi flaticon-people-4"></i>
        <h4>Who's in your kitchen?</h4>
      </div>
      <%=  render 'form' %>
    </div>
  </div>

</div>