config/routes.rb
# == Route Map
#
#                           Prefix Verb     URI Pattern                             Controller#Action
#                 new_user_session GET      /users/sign_in(.:format)                devise/sessions#new
#                     user_session POST     /users/sign_in(.:format)                devise/sessions#create
#             destroy_user_session DELETE   /users/sign_out(.:format)               devise/sessions#destroy
# user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)          users/omniauth_callbacks#passthru
#  user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format) users/omniauth_callbacks#facebook
#                new_user_password GET      /users/password/new(.:format)           devise/passwords#new
#               edit_user_password GET      /users/password/edit(.:format)          devise/passwords#edit
#                    user_password PATCH    /users/password(.:format)               devise/passwords#update
#                                  PUT      /users/password(.:format)               devise/passwords#update
#                                  POST     /users/password(.:format)               devise/passwords#create
#         cancel_user_registration GET      /users/cancel(.:format)                 devise/registrations#cancel
#            new_user_registration GET      /users/sign_up(.:format)                devise/registrations#new
#           edit_user_registration GET      /users/edit(.:format)                   devise/registrations#edit
#                user_registration PATCH    /users(.:format)                        devise/registrations#update
#                                  PUT      /users(.:format)                        devise/registrations#update
#                                  DELETE   /users(.:format)                        devise/registrations#destroy
#                                  POST     /users(.:format)                        devise/registrations#create
#                             root GET      /                                       pages#home
#                           groups POST     /groups(.:format)                       groups#create
#                        new_group GET      /groups/new(.:format)                   groups#new
#                            meals GET      /meals(.:format)                        meals#index
#                                  POST     /meals(.:format)                        meals#create
#                         new_meal GET      /meals/new(.:format)                    meals#new
#                        edit_meal GET      /meals/:id/edit(.:format)               meals#edit
#                             meal GET      /meals/:id(.:format)                    meals#show
#                                  PATCH    /meals/:id(.:format)                    meals#update
#                                  PUT      /meals/:id(.:format)                    meals#update
#                                  DELETE   /meals/:id(.:format)                    meals#destroy
#

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :groups do
    get 'users', defaults: { format: :json }
  end

  resources :meals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
<% if flash[:success] %>
  <div class="alert alert-secondary alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:success] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/ahogue1" target="blank"><i class="fa fa-github"></i></a>
    <a href="https://www.linkedin.com/in/aehogue/" target="blank"><i class="fa fa-linkedin"></i></a>
  </div>

  <%= link_to "http://www.amyhogue.com/",  target: :_blank do %>
    <div class="yam-footer">
      <p>Powered By</p>
      <%= image_tag("yam.png")%>
      <p>Yam</p>
    </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <%= link_to "New Group", new_group_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to "Planner", meals_path, class: "navbar-wagon-item navbar-wagon-link planner-btn btn btn-primary" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag avatar_url(current_user), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle mobile-dropdown" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <% if user_signed_in? %>
          <li><a href="#">New Group</a></li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
          </li>
        <% else %>
          <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>

      </ul>
    </div>
  </div>
</div>