config/routes.rb
# == Route Map
#
#                           Prefix Verb     URI Pattern                             Controller#Action
#                 new_user_session GET      /users/sign_in(.:format)                devise/sessions#new
#                     user_session POST     /users/sign_in(.:format)                devise/sessions#create
#             destroy_user_session DELETE   /users/sign_out(.:format)               devise/sessions#destroy
# user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)          users/omniauth_callbacks#passthru
#  user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format) users/omniauth_callbacks#facebook
#                new_user_password GET      /users/password/new(.:format)           devise/passwords#new
#               edit_user_password GET      /users/password/edit(.:format)          devise/passwords#edit
#                    user_password PATCH    /users/password(.:format)               devise/passwords#update
#                                  PUT      /users/password(.:format)               devise/passwords#update
#                                  POST     /users/password(.:format)               devise/passwords#create
#         cancel_user_registration GET      /users/cancel(.:format)                 devise/registrations#cancel
#            new_user_registration GET      /users/sign_up(.:format)                devise/registrations#new
#           edit_user_registration GET      /users/edit(.:format)                   devise/registrations#edit
#                user_registration PATCH    /users(.:format)                        devise/registrations#update
#                                  PUT      /users(.:format)                        devise/registrations#update
#                                  DELETE   /users(.:format)                        devise/registrations#destroy
#                                  POST     /users(.:format)                        devise/registrations#create
#                             root GET      /                                       pages#home
#                           groups POST     /groups(.:format)                       groups#create
#                        new_group GET      /groups/new(.:format)                   groups#new
#                            meals GET      /meals(.:format)                        meals#index
#                                  POST     /meals(.:format)                        meals#create
#                         new_meal GET      /meals/new(.:format)                    meals#new
#                        edit_meal GET      /meals/:id/edit(.:format)               meals#edit
#                             meal GET      /meals/:id(.:format)                    meals#show
#                                  PATCH    /meals/:id(.:format)                    meals#update
#                                  PUT      /meals/:id(.:format)                    meals#update
#                                  DELETE   /meals/:id(.:format)                    meals#destroy
#

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  resources :groups do
    get 'users', defaults: { format: :json }
  end

  resources :meals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id         :integer          not null, primary key
#  date       :date
#  name       :string
#  category   :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  group_id   :integer
#  recipe_id  :integer
#
# Indexes
#
#  index_meals_on_group_id   (group_id)
#  index_meals_on_recipe_id  (recipe_id)
#  index_meals_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (group_id => groups.id)
#  fk_rails_...  (recipe_id => recipes.id)
#  fk_rails_...  (user_id => users.id)
#

class Meal < ApplicationRecord
  belongs_to :user
  belongs_to :group
  belongs_to :recipe, optional: true
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    @meal = Meal.new
    @group = Group.new
    @today = Date.today
    @groups = current_user.groups
    @week_days = @today.beginning_of_week..@today.end_of_week

    if @groups.any?
      @meals = Meal.where(group: @groups, date: @week_days)
    else
      redirect_to new_group_path, flash: { success: "You don't have a group yet, let's make one!" }
    end
  end

  def show
    @meal = Meal.find(params[:id])

    if @meal.recipe_id
      @recipe = @meal.recipe
    else

      if @meal.name == ""
        @recipes = EdamamService.new.search(@meal.category)
      else
        @recipes = EdamamService.new.search(@meal.name)
      end

    end
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def update
    @meal = Meal.find(params[:id])

    @recipe = Recipe.find_by(edamam_id: params[:edamam_id])

    unless @recipe
      @recipe = EdamamService.new.find(params[:edamam_id])
      @recipe.save
    end

    @meal.recipe = @recipe
    @meal.name = @recipe.label

    if @meal.save
      redirect_to meal_path(@meal)
    else
      redirect_to meal_path(@meal), error: 'Recipe not added to the meal'
    end
  end

  def create
    @meal = Meal.new(meal_params)

    if @meal.save
      redirect_to meals_path
    else
      redirect_to meals_path, error: "Meal not saved complete all fields"
    end

  end


  private

  def meal_params
    params.require(:meal).permit(:category, :date, :name, :user_id, :group_id, :recipe_id)
  end

end

app/views/meals/_form.html.erb
<%= simple_form_for(meal) do |f| %>
  <%= f.input :name, label: "Meal:", placeholder: "Pizza, Tacos, Sesame Chicken..." %>
  <%= f.input :date, as: :text, as: :hidden %>
  <%= f.input :category, label: "Not sure yet? Enter a category and we will help", placeholder: "Italian, Vegetarian..."%>

  <div class="form-group select required meal_user">
    <label class="control-label select required" for="meal_user_id">
      <abbr title="required">*</abbr> Cook:
    </label>
    <div class="loading-spinner">
    <i class="fa fa-spinner fa-spin" aria-hidden="true"></i>
    </div>
    <select class="form-control select required hidden" name="meal[user_id]" id="meal_user_id">
    </select>
  </div>

  <%= f.association :group, label_method: :name, as: :hidden %>

  <%= f.submit 'Create', class: "btn btn-primary" %>
<% end %>

app/views/meals/_recipe.html.erb
<div class="flex-center date-links">
  <%=  link_to "Planner >   ", meals_path %>
  <h5><%=  @meal.group.name %></h5>
</div>

<div class="search-title">
  <% if @meal.name != '' %>
    <h2>We're having <%= @meal.name %> on <%= @meal.date.strftime("%A") %>!</h2>
  <% else %>
    <h2>We're having <%= @meal.category %> food on <%= @meal.date.strftime("%A") %>!</h2>
  <% end %>
  <h4> Find a recipe you like and save it</h4>
  <%= image_tag avatar_url(@meal.user), class: "avatar-md" %>
  <h4 class="fi flaticon-people-6"><%= @meal.user.username %></h4>
</div>

<div class="container search-container">
  <div class="recipe-row row">
    <% @recipes.each do |recipe| %>
      <div class="col-xs-6 col-sm-4 col-md-3">
        <%= link_to recipe.url,  target: :_blank do %>
        <div class="recipe-card card">
          <%= image_tag recipe.image %>
          <div class="recipe-card-details">
            <div class="recipe-card-name">
              <h4 title="<%=recipe.label%>"><%= truncate(recipe.label, length: 37, separator: " ") %></h4>
            </div>
            <p>From: <%= recipe.source %></p>
            <p class = "limit-line-height"> <%= recipe.health_labels %></p>
          </div>
        </div>
        <% end %>
        <%= link_to "Save Recipe", meal_path(@meal, edamam_id: recipe.edamam_id), method: :patch, class: "green" %>
      </div>
    <% end %>
  </div>
</div>

app/views/meals/_recipes.html.erb
<div class="date-links">
 <div class="flex-center">
   <%=  link_to "Planner >  ", meals_path %>
   <h5><%=  @meal.group.name %></h5>
 </div>
 <h3><%= @meal.date.strftime("%A %d") %></h3>
</div>

<div class="recipe-container">

 <div class="recipe-image">
   <%= image_tag @recipe.image %>
 </div>

 <div>
   <div class="recipe-heading">
     <h1><%= @meal.name %></h1>
   </div>

   <div class="recipe-show">


     <div class="recipe-details">
       <p>Source: <%= @recipe.source %></p>
       <p>Servings: <%= @recipe.yield %>
       <p><%= @recipe.health_labels %></p>
       <%= link_to "View Recipe", @recipe.url, class: "btn btn-primary", target: :blank %>
       <%= link_to "edit meal", edit_meal_path, class: "btn btn-primary", target: :blank %>
     </div>

     <div class= "meal-user">
       <%= image_tag avatar_url(@meal.user), class: "avatar-md" %>
       <h4 class="fi flaticon-people-6"><%= @meal.user.username %></h4>
     </div>
   </div>
 </div>

</div>

app/views/meals/edit.html.erb
<h1>Meal Edit page</h1>

app/views/meals/index.html.erb
<div class="container index-container">
  <h3 class="fi flaticon-time-1 right-align">
  <%= @week_days.first.strftime("%B %e") %> - <%= @week_days.last.strftime("%B %e") %>
  </h3>

  <% @groups.each do |group| %>

    <h3 class = "fi flaticon-people-4"> <%= group.name %></h3>
    <%= link_to "edit", edit_group_path(group) %>

    <div class="row no-gutters index-row">

      <% @week_days.each do |day| %>

        <div class="col-xs-12 col-sm-4 seven-columns">
          <div class="card index-card">
            <div class ="card-heading">
              <%= day.strftime("%A %e") %>
            </div>

            <% meal = @meals.find { |meal| meal.date == day && meal.group_id == group.id } %>

            <% if meal %>

              <%= link_to meal_path(meal.id) do %>
                <div class="card-body">

                  <div class="meal-link">
                    <%= image_tag avatar_url(meal.user), class: "avatar-md"%>
                    <p class="fi flaticon-people-6"><%= meal.user.username %> </p>
                     <i class="fi flaticon-tool"></i>
                      <%= meal.name %>
                  </div>
                </div>
              <% end %>

            <% else %>
              <div class="card-body" role="button" class="" data-container="body" data-toggle="popover" data-placement="bottom" data-group-id="<%= group.id %>" data-day="<%= day %>">
               <i class="fa fa-plus-circle fa-2x" aria-hidden="true"></i>
              </div>
            <% end %>

          </div>
        </div>

      <% end %>

    </div>

  <% end %>

</div>


<div class="hidden-form">
  <%= render 'form', meal: @meal %>
</div>

app/views/meals/new.html.erb
<h1>New Meals page! </h1>

<%= simple_form_for(@meal) do |f| %>
  <%= f.input :name %>
  <%= f.input :date %>
  <%= f.input :category %>
  <%= f.association :user, label_method: :username %>
  <%= f.association :group, label_method: :name %>

  <%= f.submit 'Create', class: "btn btn-primary" %>
  <% end %>

app/views/meals/show.html.erb
<div class="meal-container">


    <!-- Only visible if user hasn't saved a recipe -->
  <% if @recipes %>
    <%= render "recipe" %>

<!-- Only visible if user has saved one recipe for the day -->
  <% else %>
    <%= render "recipes" %>

  <% end %>

<!-- list recipe ingredients if recipe has been saved for the day -->
  <% if @recipes.nil? %>
    <div class="ingredient-list">
      <h3>Ingredients</h3>
      <% @recipe.ingredients.each do |ingredient| %>
        <p> <%= ingredient.name %></p>
      <% end %>
    </div>
  <% end %>
</div>